apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: sachirjn/docker-demo:6
          env:
            - name: RANDOM_IMAGE_URL
              value: http://172.20.33.126:30200
