apiVersion: v1
kind: Service
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: docker-demo
