apiVersion: v1
kind: Service
metadata:
  name: random-image-url
spec:
  type: ClusterIP #only accessible in the cluster
  selector:
    app: random-image-url
  ports:
    - protocol: TCP
      port: 30200
      targetPort: 30200
